export const animals = [
  {
    "name": "African Elephant",
    "scientificName": "Loxodonta africana",
    "category": "Mammal",
    "region": "Africa",
    "habitat": "Savanna, Forest",
    "diet": "Herbivore",
    "weightKg": 6000,
    "lifespanYears": 70,
    "populationEstimate": 415000,
    "conservationStatus": "Vulnerable",
    "description": "The largest land animal, known for its intelligence and strong social bonds."
  },
  {
    "name": "Bengal Tiger",
    "scientificName": "Panthera tigris tigris",
    "category": "Mammal",
    "region": "Asia",
    "habitat": "Forest, Grassland",
    "diet": "Carnivore",
    "weightKg": 240,
    "lifespanYears": 15,
    "populationEstimate": 2500,
    "conservationStatus": "Endangered",
    "description": "A majestic big cat with distinctive orange and black stripes."
  },
  {
    "name": "Blue Whale",
    "scientificName": "Balaenoptera musculus",
    "category": "Mammal",
    "region": "Global Oceans",
    "habitat": "Ocean",
    "diet": "Carnivore",
    "weightKg": 200000,
    "lifespanYears": 100,
    "populationEstimate": 25000,
    "conservationStatus": "Endangered",
    "description": "The largest animal on Earth, feeding primarily on krill."
  },
  {
    "name": "Bald Eagle",
    "scientificName": "Haliaeetus leucocephalus",
    "category": "Bird",
    "region": "North America",
    "habitat": "Forest, Coastline",
    "diet": "Carnivore",
    "weightKg": 5.5,
    "lifespanYears": 20,
    "populationEstimate": 70000,
    "conservationStatus": "Least Concern",
    "description": "A symbol of freedom with a striking white head and powerful wings."
  },
  {
    "name": "Emperor Penguin",
    "scientificName": "Aptenodytes forsteri",
    "category": "Bird",
    "region": "Antarctica",
    "habitat": "Ice, Ocean",
    "diet": "Carnivore",
    "weightKg": 30,
    "lifespanYears": 20,
    "populationEstimate": 600000,
    "conservationStatus": "Near Threatened",
    "description": "The tallest penguin species, adapted to harsh Antarctic winters."
  },
  {
    "name": "Scarlet Macaw",
    "scientificName": "Ara macao",
    "category": "Bird",
    "region": "South America",
    "habitat": "Rainforest",
    "diet": "Herbivore",
    "weightKg": 1,
    "lifespanYears": 50,
    "populationEstimate": 50000,
    "conservationStatus": "Least Concern",
    "description": "A vibrant parrot known for its bright red, yellow, and blue feathers."
  },
  {
    "name": "Komodo Dragon",
    "scientificName": "Varanus komodoensis",
    "category": "Reptile",
    "region": "Indonesia",
    "habitat": "Island Grassland",
    "diet": "Carnivore",
    "weightKg": 90,
    "lifespanYears": 30,
    "populationEstimate": 3000,
    "conservationStatus": "Vulnerable",
    "description": "The largest lizard, with a venomous bite and powerful tail."
  },
  {
    "name": "Green Sea Turtle",
    "scientificName": "Chelonia mydas",
    "category": "Reptile",
    "region": "Global Oceans",
    "habitat": "Ocean, Coastline",
    "diet": "Herbivore",
    "weightKg": 160,
    "lifespanYears": 80,
    "populationEstimate": 85000,
    "conservationStatus": "Endangered",
    "description": "A migratory sea turtle with a diet shifting from carnivorous to herbivorous as it matures."
  },
  {
    "name": "Nile Crocodile",
    "scientificName": "Crocodylus niloticus",
    "category": "Reptile",
    "region": "Africa",
    "habitat": "River, Wetland",
    "diet": "Carnivore",
    "weightKg": 500,
    "lifespanYears": 70,
    "populationEstimate": 250000,
    "conservationStatus": "Least Concern",
    "description": "A formidable predator lurking in African waterways."
  },
  {
    "name": "Poison Dart Frog",
    "scientificName": "Dendrobatidae (family)",
    "category": "Amphibian",
    "region": "South America",
    "habitat": "Rainforest",
    "diet": "Carnivore",
    "weightKg": 0.002,
    "lifespanYears": 10,
    "populationEstimate": 100000,
    "conservationStatus": "Vulnerable",
    "description": "Tiny but deadly, with bright colors warning of its toxic skin."
  },
  {
    "name": "Axolotl",
    "scientificName": "Ambystoma mexicanum",
    "category": "Amphibian",
    "region": "Mexico",
    "habitat": "Lake",
    "diet": "Carnivore",
    "weightKg": 0.3,
    "lifespanYears": 15,
    "populationEstimate": 1000,
    "conservationStatus": "Critically Endangered",
    "description": "A unique salamander that retains its larval features throughout life."
  },
  {
    "name": "Red-Eyed Tree Frog",
    "scientificName": "Agalychnis callidryas",
    "category": "Amphibian",
    "region": "Central America",
    "habitat": "Rainforest",
    "diet": "Carnivore",
    "weightKg": 0.01,
    "lifespanYears": 5,
    "populationEstimate": 50000,
    "conservationStatus": "Least Concern",
    "description": "Known for its vivid green body and striking red eyes."
  },
  {
    "name": "Great White Shark",
    "scientificName": "Carcharodon carcharias",
    "category": "Fish",
    "region": "Global Oceans",
    "habitat": "Ocean",
    "diet": "Carnivore",
    "weightKg": 2000,
    "lifespanYears": 70,
    "populationEstimate": 3500,
    "conservationStatus": "Vulnerable",
    "description": "An apex predator with a fearsome reputation."
  },
  {
    "name": "Clownfish",
    "scientificName": "Amphiprioninae (subfamily)",
    "category": "Fish",
    "region": "Indo-Pacific",
    "habitat": "Coral Reef",
    "diet": "Omnivore",
    "weightKg": 0.25,
    "lifespanYears": 6,
    "populationEstimate": 1000000,
    "conservationStatus": "Least Concern",
    "description": "Bright orange fish living symbiotically with sea anemones."
  },
  {
    "name": "Electric Eel",
    "scientificName": "Electrophorus electricus",
    "category": "Fish",
    "region": "South America",
    "habitat": "River",
    "diet": "Carnivore",
    "weightKg": 20,
    "lifespanYears": 15,
    "populationEstimate": 50000,
    "conservationStatus": "Least Concern",
    "description": "Capable of generating electric shocks to stun prey."
  },
  {
    "name": "Monarch Butterfly",
    "scientificName": "Danaus plexippus",
    "category": "Insect",
    "region": "North America",
    "habitat": "Forest, Grassland",
    "diet": "Herbivore",
    "weightKg": 0.0005,
    "lifespanYears": 0.5,
    "populationEstimate": 50000000,
    "conservationStatus": "Near Threatened",
    "description": "Famous for its long migration and striking orange wings."
  },
  {
    "name": "Goliath Beetle",
    "scientificName": "Goliathus goliatus",
    "category": "Insect",
    "region": "Africa",
    "habitat": "Rainforest",
    "diet": "Herbivore",
    "weightKg": 0.1,
    "lifespanYears": 1,
    "populationEstimate": 100000,
    "conservationStatus": "Least Concern",
    "description": "One of the heaviest insects, with a robust, armored body."
  },
  {
    "name": "Honey Bee",
    "scientificName": "Apis mellifera",
    "category": "Insect",
    "region": "Global",
    "habitat": "Forest, Grassland",
    "diet": "Herbivore",
    "weightKg": 0.0001,
    "lifespanYears": 0.5,
    "populationEstimate": 8000000000,
    "conservationStatus": "Not Evaluated",
    "description": "Vital pollinators producing honey in complex hives."
  },
  {
    "name": "Giant Panda",
    "scientificName": "Ailuropoda melanoleuca",
    "category": "Mammal",
    "region": "Asia",
    "habitat": "Mountain Forest",
    "diet": "Herbivore",
    "weightKg": 100,
    "lifespanYears": 20,
    "populationEstimate": 1800,
    "conservationStatus": "Vulnerable",
    "description": "A beloved bear species with a distinctive black-and-white coat."
  },
  {
    "name": "Arctic Fox",
    "scientificName": "Vulpes lagopus",
    "category": "Mammal",
    "region": "Arctic",
    "habitat": "Tundra",
    "diet": "Carnivore",
    "weightKg": 4,
    "lifespanYears": 10,
    "populationEstimate": 100000,
    "conservationStatus": "Least Concern",
    "description": "A small fox with thick fur adapted to icy environments."
  },
  {
    "name": "Andean Condor",
    "scientificName": "Vultur gryphus",
    "category": "Bird",
    "region": "South America",
    "habitat": "Mountain",
    "diet": "Carnivore",
    "weightKg": 15,
    "lifespanYears": 70,
    "populationEstimate": 10000,
    "conservationStatus": "Near Threatened",
    "description": "One of the largest flying birds, soaring over the Andes."
  },
  {
    "name": "Galápagos Tortoise",
    "scientificName": "Chelonoidis nigra",
    "category": "Reptile",
    "region": "Galápagos Islands",
    "habitat": "Island Grassland",
    "diet": "Herbivore",
    "weightKg": 250,
    "lifespanYears": 150,
    "populationEstimate": 15000,
    "conservationStatus": "Vulnerable",
    "description": "A long-lived giant tortoise unique to the Galápagos."
  },
  {
    "name": "Lionfish",
    "scientificName": "Pterois volitans",
    "category": "Fish",
    "region": "Indo-Pacific",
    "habitat": "Coral Reef",
    "diet": "Carnivore",
    "weightKg": 1.2,
    "lifespanYears": 15,
    "populationEstimate": 500000,
    "conservationStatus": "Least Concern",
    "description": "A venomous fish with striking red and white stripes."
  },
  {
    "name": "Tarantula",
    "scientificName": "Theraphosidae (family)",
    "category": "Insect",
    "region": "Global",
    "habitat": "Forest, Desert",
    "diet": "Carnivore",
    "weightKg": 0.05,
    "lifespanYears": 25,
    "populationEstimate": 1000000,
    "conservationStatus": "Not Evaluated",
    "description": "A large, hairy spider known for its impressive size and lifespan."
  },
  {
    "name": "Polar Bear",
    "scientificName": "Ursus maritimus",
    "category": "Mammal",
    "region": "Arctic",
    "habitat": "Ice, Ocean",
    "diet": "Carnivore",
    "weightKg": 600,
    "lifespanYears": 30,
    "populationEstimate": 26000,
    "conservationStatus": "Vulnerable",
    "description": "A massive bear adapted to life on Arctic sea ice."
  },
  {
    "name": "Red Kangaroo",
    "scientificName": "Macropus rufus",
    "category": "Mammal",
    "region": "Australia",
    "habitat": "Desert, Grasslands",
    "diet": "Herbivore",
    "weightKg": 85,
    "lifespanYears": 23,
    "populationEstimate": 11000000,
    "conservationStatus": "Least Concern",
    "description": "The largest marsupial, known for its powerful legs and high-speed hopping."
  },
  {
    "name": "Snow Leopard",
    "scientificName": "Panthera uncia",
    "category": "Mammal",
    "region": "Central Asia",
    "habitat": "Mountains",
    "diet": "Carnivore",
    "weightKg": 55,
    "lifespanYears": 15,
    "populationEstimate": 4000,
    "conservationStatus": "Vulnerable",
    "description": "A rare and elusive big cat adapted to high-altitude life."
  },
  {
    "name": "Green Anaconda",
    "scientificName": "Eunectes murinus",
    "category": "Reptile",
    "region": "South America",
    "habitat": "Swamp, River",
    "diet": "Carnivore",
    "weightKg": 250,
    "lifespanYears": 10,
    "populationEstimate": "Unknown",
    "conservationStatus": "Least Concern",
    "description": "The world's heaviest snake, known for its immense strength and aquatic lifestyle."
  },
  {
    "name": "Cheetah",
    "scientificName": "Acinonyx jubatus",
    "category": "Mammal",
    "region": "Africa",
    "habitat": "Savanna, Grasslands",
    "diet": "Carnivore",
    "weightKg": 72,
    "lifespanYears": 12,
    "populationEstimate": 7100,
    "conservationStatus": "Vulnerable",
    "description": "The fastest land animal, capable of reaching speeds up to 120 km/h."
  },
  {
    "name": "Giraffe",
    "scientificName": "Giraffa camelopardalis",
    "category": "Mammal",
    "region": "Africa",
    "habitat": "Savanna, Woodlands",
    "diet": "Herbivore",
    "weightKg": 1192,
    "lifespanYears": 25,
    "populationEstimate": 117000,
    "conservationStatus": "Vulnerable",
    "description": "The tallest land animal, known for its long neck and spotted coat."
  },
  {
    "name": "European Brown Bear",
    "scientificName": "Ursus arctos arctos",
    "category": "Mammal",
    "region": "Europe",
    "habitat": "Forest, Mountain",
    "diet": "Omnivore",
    "weightKg": 300,
    "lifespanYears": 30,
    "populationEstimate": 17000,
    "conservationStatus": "Least Concern",
    "description": "A large bear found across European forests and mountains."
  },
  {
    "name": "Eurasian Lynx",
    "scientificName": "Lynx lynx",
    "category": "Mammal",
    "region": "Europe",
    "habitat": "Forest",
    "diet": "Carnivore",
    "weightKg": 25,
    "lifespanYears": 17,
    "populationEstimate": 10000,
    "conservationStatus": "Least Concern",
    "description": "A stealthy feline with tufted ears and thick fur for cold climates."
  },
  {
    "name": "Common Kingfisher",
    "scientificName": "Alcedo atthis",
    "category": "Bird",
    "region": "Europe",
    "habitat": "River, Wetland",
    "diet": "Carnivore",
    "weightKg": 0.04,
    "lifespanYears": 7,
    "populationEstimate": 500000,
    "conservationStatus": "Least Concern",
    "description": "A small bird with brilliant blue and orange plumage, often seen diving for fish."
  },
  {
    "name": "European Adder",
    "scientificName": "Vipera berus",
    "category": "Reptile",
    "region": "Europe",
    "habitat": "Forest, Grassland",
    "diet": "Carnivore",
    "weightKg": 0.1,
    "lifespanYears": 15,
    "populationEstimate": 1000000,
    "conservationStatus": "Least Concern",
    "description": "The only venomous snake widespread in Europe, with a distinctive zigzag pattern."
  },
  {
    "name": "European Stag Beetle",
    "scientificName": "Lucanus cervus",
    "category": "Insect",
    "region": "Europe",
    "habitat": "Forest",
    "diet": "Herbivore",
    "weightKg": 0.005,
    "lifespanYears": 3,
    "populationEstimate": 500000,
    "conservationStatus": "Near Threatened",
    "description": "A large beetle with impressive antler-like mandibles, found in old woodlands."
  },
  {
    "name": "Siberian Tiger",
    "scientificName": "Panthera tigris altaica",
    "category": "Mammal",
    "region": "Asia",
    "habitat": "Forest, Taiga",
    "diet": "Carnivore",
    "weightKg": 300,
    "lifespanYears": 18,
    "populationEstimate": 500,
    "conservationStatus": "Endangered",
    "description": "The largest tiger subspecies, adapted to cold forests of eastern Russia."
  },
  {
    "name": "Indian Elephant",
    "scientificName": "Elephas maximus indicus",
    "category": "Mammal",
    "region": "Asia",
    "habitat": "Forest, Grassland",
    "diet": "Herbivore",
    "weightKg": 4000,
    "lifespanYears": 60,
    "populationEstimate": 30000,
    "conservationStatus": "Endangered",
    "description": "A smaller relative of the African elephant, revered in Asian cultures."
  },
  {
    "name": "Japanese Crane",
    "scientificName": "Grus japonensis",
    "category": "Bird",
    "region": "Asia",
    "habitat": "Wetland",
    "diet": "Omnivore",
    "weightKg": 9,
    "lifespanYears": 30,
    "populationEstimate": 3000,
    "conservationStatus": "Endangered",
    "description": "A striking red-crowned bird symbolizing luck and longevity in Japan."
  },
  {
    "name": "King Cobra",
    "scientificName": "Ophiophagus hannah",
    "category": "Reptile",
    "region": "Asia",
    "habitat": "Forest",
    "diet": "Carnivore",
    "weightKg": 6,
    "lifespanYears": 20,
    "populationEstimate": 50000,
    "conservationStatus": "Vulnerable",
    "description": "The longest venomous snake, capable of standing upright to intimidate."
  },
  {
    "name": "Asian Giant Hornet",
    "scientificName": "Vespa mandarinia",
    "category": "Insect",
    "region": "Asia",
    "habitat": "Forest",
    "diet": "Carnivore",
    "weightKg": 0.05,
    "lifespanYears": 1,
    "populationEstimate": 1000000,
    "conservationStatus": "Not Evaluated",
    "description": "A massive hornet with a painful sting, known for preying on other insects."
  },
  {
    "name": "Hippopotamus",
    "scientificName": "Hippopotamus amphibius",
    "category": "Mammal",
    "region": "Africa",
    "habitat": "River, Wetland",
    "diet": "Herbivore",
    "weightKg": 3000,
    "lifespanYears": 40,
    "populationEstimate": 125000,
    "conservationStatus": "Vulnerable",
    "description": "A massive, semi-aquatic mammal with a barrel-shaped body and powerful jaws."
  }
]